import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Header from '@/components/Header'
import Banner from '@/components/Banner'
import VisualEditing from '@/components/VisualEditing'
import { draftMode } from "next/headers";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Kaustubh's Blog",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-7xl mx-auto`}> 
        <Header />
        <Banner />
        {children}
        {draftMode().isEnabled && <VisualEditing />}
      </body>
    </html>
  )
}
